[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "magic"
dynamic = ["version"]
dependencies = ["termcolor==2.5.0"]
requires-python = ">=3.10"
description = "3D Software Synthesis Driven by Constraint-Expressive Intermediate Representation"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Topic :: Multimedia :: Graphics :: 3D Modeling",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.optional-dependencies]
blip = ["defaultlist==1.2.0"]
dev = ["black==24.10.0", "seaborn==0.13.2"]
extra = ["z3-solver==4.14.1.0"]
gemini = ["google-generativeai==0.8.3"]
gen = [
    "cloudpickle==3.1.1",
    "datasets==3.6.0",
    "hf-xet==1.1.2",
    "huggingface_hub==0.31.4",
    "json_repair==0.40.0",
    "open3d==0.19.0",
    "open_clip_torch==2.28.0",
    "openai==1.66.3",
    "opencv-python==4.11.0.86",
    "opencv-python-headless==4.5.5.64",
    "pydantic==2.9.2",
    "pyyaml==6.0.2",
    "rtree==1.4.0",
    "scipy==1.14.1",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "torchvision==0.21.0",
    "transformers==4.52.3",
    "trimesh==4.5.1",
]
objathor = [
    "attrs==24.2.0",
    "compress_json==1.1.0",
    "compress_pickle==2.1.0",
    "filelock==3.16.1",
    "sentence-transformers==4.1.0",
]
objaverse = ["objaverse==0.1.7"]
shap-e = [
    "shap-e@git+https://github.com/openai/shap-e.git@50131012ee11c9d2617f3886c10f000d3c7a3b43",
]

[project.scripts]
brender = "magic.blender:_cli"
download-objathor_annotations = "magic.object.objrtv.objathor.dataset.download_annotations:_cli"
download-objathor_assets = "magic.object.objrtv.objathor.dataset.download_assets:_cli"
download-objathor_features = "magic.object.objrtv.objathor.dataset.download_features:_cli"
download-objathor_holodeck = "magic.object.objrtv.objathor.dataset.download_holodeck_base:_cli"
magic = "magic.generation.main:_cli"
magic-eval = "magic.generation.evaluation.evaluate:_cli"
magic-evalsum = "magic.generation.evaluation.summarize:_cli"
magicdata = "magic.dataset.main:_cli"

[tool.setuptools]
packages = ["magic"]

[tool.setuptools.dynamic]
version = { attr = "magic.__version__" }

[tool.black]
line-length = 119
